services:
  # Frontend - React/TypeScript 
  frontend:
    container_name: ${PROJECT_NAME}-frontend
    restart: always
    environment:
      - TZ=Australia/Perth
    networks:
      - default
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      args:
        project: modules/frontend
    ports:
      - "5173:5173"
    volumes:
      - ./modules/frontend:/app
      - /app/node_modules
    working_dir: /app

  # Backend - ASP.NET
  backend:
    container_name: ${PROJECT_NAME}-backend
    environment:
      - TZ=Australia/Perth
    networks:
      - default
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
      args:
        project: modules/backend
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./modules/backend:/app
    working_dir: /app

  # Nginx - Reverse proxy
  nginx:
    container_name: ${PROJECT_NAME}-nginx
    depends_on:
      - frontend
      - backend
    image: nginx:latest
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - default
    environment:
      - TZ=Australia/Perth

volumes:
  db_data:
  redis_data:

networks:
  default:
    driver: bridge
    name: ${PROJECT_NAME}
